# latest release
image: hyperledger/iroha:latest
manifests:
  -
    image: hyperledger/iroha:x86_64-latest
    platform:
      architecture: amd64
      os: linux
      features:
        - sse
  -
    image: hyperledger/iroha:armv7l-latest
    platform:
      architecture: arm
      os: linux
      variant: v7
  -
    image: hyperledger/iroha:aarch64-latest
    platform:
      architecture: arm64
      os: linux

# master branch
image: hyperledger/iroha:master
manifests:
  -
    image: hyperledger/iroha:x86_64-master
    platform:
      architecture: amd64
      os: linux
      features:
        - sse
  -
    image: hyperledger/iroha:armv7l-master
    platform:
      architecture: arm
      os: linux
      variant: v7
  -
    image: hyperledger/iroha:aarch64-master
    platform:
      architecture: arm64
      os: linux

# develop branch, build env
image: hyperledger/iroha:develop-build
manifests:
  -
    image: hyperledger/iroha:x86_64-develop-build
    platform:
      architecture: amd64
      os: linux
      features:
        - sse
  -
    image: hyperledger/iroha:armv7l-develop-build
    platform:
      architecture: arm
      os: linux
      variant: v7
  -
    image: hyperledger/iroha:aarch64-develop-build
    platform:
      architecture: arm64
      os: linux
